name: f2g
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  # google_sign_in:
  google_sign_in: ^6.2.1
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.1
  google_fonts: ^6.3.0
  pinput: ^5.0.1
  gradient_borders: ^1.0.1
  image_picker: ^1.2.0
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  intl: ^0.20.2
  change_app_package_name: ^1.5.0
  firebase_auth: ^6.1.0
  loading_animation_widget: ^1.3.0
  fluttertoast: ^9.0.0
  firebase_messaging: ^16.0.2
  uuid: ^4.5.1
  path: ^1.9.1
  google_maps_flutter: ^2.13.1
  geocoding: ^4.0.0
  shared_preferences: ^2.5.3
  geolocator: ^14.0.2
  http: ^1.5.0
  app_settings: ^6.1.1
  permission_handler: ^12.0.1
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: HelveticaNowDisplay
      fonts:
        - asset: assets/fonts/HelveticaNowDisplay-Bold.ttf
        - asset: assets/fonts/HelveticaNowDisplay-Medium.ttf
        - asset: assets/fonts/HelveticaNowDisplay-Regular.ttf
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Medium.otf

flutter_assets:
  assets_path: assets/images/
  output_path: lib/constants/
  filename: app_images.dart
  field_prefix: ""
