Map<String, String> enUS = {
  "findingNextPlan": "Finding your next plan...",
  "getHelp": "Get Help",
  "welcomeBack": "Welcome Back!",
  "loginSubtitle": "Please enter the credentials to get started.",
  "emailAddress": "Email address",
  "password": "Password",
  "forgotPassword": "Forgot Password?",
  "rememberMe": "Remember me",
  "continueButton": "Continue",
  "orSignIn": "or sign in",
  "dontHaveAccount": "Don't have an Account?",
  "register": "Register",
  "forgotPasswordTitle": "Forgot Password",
  "forgotPasswordSubtitle": "Please enter the email address that start's with",
  "sendVerificationLink": "Send Verification Link",
  "backTo": "Back to",
  "login": "Login",
  "mailSent": "Mail Sent !",
  "mailSentDescription":
      "We have sent an mail on your given email address. Please verify and reset your password.",
  "checkMail": "Check mail",
  "resetPassword": "Reset Password",
  "resetPasswordSubtitle":
      "Please create your new password. Do not share with anyone in your circle.",
  "backToLogin": "Back to Login",
  "accountCreated": "Account Created!",
  "accountCreatedDescription":
      "You have successfully created your account. Enjoy the ride",
  "goToHomePage": "Go the Home Page",
  "personalInformation": "Personal Information",
  "personalInfoSubtitle":
      "Please enter your personal information to move further.",
  "uploadProfilePhoto": "Upload Profile Photo",
  "uploadProfilePhotoSubtitle": "Please upload your face image.",
  "basicInformation": "BASIC INFORMATION",
  "fullName": "Full Name",
  "gender": "Gender",
  "dateOfBirth": "Date of Birth",
  "ageRestriction": "You must be 18+ to use this app.",
  "confirm": "Confirm",
  "location": "Location",
  "biography": "Biography",
  "autoSendPlanInfo": "Auto-send plan info to contact when user joins a plan",
  "emergencyContactInformation": "Emergency Contact Information",
  "emergencyContactSubtitle":
      "Please enter your contact information in case of any emergency.",
  "contactName": "Contact Name",
  "emergencyPhoneNumber": "Emergency Phone number",
  "relationshipType": "Relationship Type",
  "freePlan": "Free Plan",
  "freePlanSubtitle": "Enjoy our amazing and affordable subscription plans.",
  "freePlanLimit": "Limit of 2 plans per week",
  "freePlanFilters": "Filters: Distance + Category only",
  "freePlanNotifications":
      "Notifications after reaching the weekly limit recommending upgrade.",
  "freeMonthPremiumTrial": "FREE 1 MONTH PREMIUM TRIAL",
  "startFreeTrial": "Start Free Trial",
  "premiumPackage": "PREMIUM PACKAGE",
  "monthly": "monthly",
  "signingInAgree": "By signing in you agree to",
  "termsAndConditions": "Terms & Conditions",
  "and": "and our",
  "privacyPolicy": "Privacy Policy",
  "selectPayment": "Select Payment",
  "selectPaymentSubtitle": "Please select the preferred payment method.",
  "applePay": "Apply Pay",
  "debitCreditCard": "Debit/Credit Card",
  "googlePay": "Google Pay",
  "americanExpress": "American Express",
  "enterCardInformation": "Enter Card Information",
  "back": "Back",
  "enterCardInfoSubtitle":
      "Please enter the card information mention on your debit or credit card.",
  "cardNumber": "Card Number",
  "cardHolderName": "Card Holder Name",
  "expiryDate": "Expiry Date",
  "cvv": "CVV",
  "goodMorning": "Good Morning!",
  "goodAfternoon": "Good Afternoon",
  "searchHere": "Search here...",
  "active": "Active",
  "expired": "Expired",
  "createNewPlan": "Create new Plan",
  "applyFilters": "Apply Filters",
  "selectPeople": "Select People",
  "to": "To",
  "selectAge": "Select Age",
  "selectDistance": "Select Distance",
  "category": "Category",
  "cultureAndLeisure": "Culture and Leisure",
  "natureAndOutdoors": "Nature and Outdoors",
  "sportsAndWellness": "Sports and Wellness",
  "socialAndLifestyle": "Social and Lifestyle",
  "creativityAndLearning": "Creativity and Learning",
  "travelAndGetaways": "Travel and Getaways",
  "gamingAndGeek": "Gaming and Geek",
  "rest": "Rest",
  "uploadPlanPhoto": "Upload Plan Photo",
  "fileSizeMax": "File size (100 mb max)",
  "upload": "Upload",
  "planTitle": "Plan Title",
  "startDate": "Start Date",
  "endDate": "End Date",
  "startTime": "Start Time",
  "endTime": "End Time",
  "maximumMembersAllowed": "Maximum Members Allowed",
  "ageMin": "Min",
  "ageMax": "Max",
  "description": "Description",
  "createPlan": "Create Plan",
  "home": "Home",
  "favorites": "Favorites",
  "myPlans": "My Plans",
  "discoverPlans": "Discover Plans",
  "notifications": "Notifications",
  "userProfile": "User Profile",
  "logout": "Logout",
  "noFavoritesYet": "No Favorites yet",
  "joinedPlans": "Joined Plans",
  "members": "Members",
  "groupProfile": "Group Profile",
  "membersInGroup": "members in this group",
  "personProfile": "Person Profile",
  "planDetails": "Plan Details",
  "completed": "Completed",
  "openGroupChat": "Open group chat",
  "dateAndTime": "Date & Time",
  "membersJoined": "Members Joined",
  "slotsLeft": "Slots Left",
  "plans": "Plans",
  "noNotificationsYet": "No Notifications Yet!",
  "noNotificationsDescription": "No Notifications to be shown yet.",
  "join": "Join",
  "participants": "Participants",
  "logoutConfirmation": "Are you sure you want to logout from this app?",
  "yesLogout": "Yes, Logout",
  "submit": "Submit",
  "deleteAccount": "Delete Account?",
  "deleteAccountConfirmation":
      "Are you sure you want to delete your account. This will erase all your current data.",
  "yesDelete": "Yes, Delete",
  "editProfile": "Edit Profile",
  "fullNameLabel": "Full name",
  "personalInformationSection": "PERSONAL INFORMATION",
  "update": "Update",
  "changePassword": "Change Password",
  "currentPassword": "Current Password",
  "newPassword": "New Password",
  "confirmNewPassword": "Confirm new password",
  "manageSubscriptions": "Manage Subscriptions",
  "enableNotifications": "Enable Notifications",
  "appFeedback": "App Feedback",
  "deleteAccountOption": "Delete Account",
  "generalSettings": "GENERAL SETTINGS",
  "helpAndSupport": "HELP & SUPPORT",
  "planFull": "Plan Full",
  "startDateAndTime": "Start Date & Time",
  "endDateAndTime": "End Date & Time",
  "planFullMessage": "The plan is full. You cannot join.",
  "leavePlan": "Leave Plan",
  "typeMessageHere": "Type your message here...",
  "gallery": "Gallery",
  "camera": "Camera",
  "pleaseAddEventImage": "Please add event image.",
  "pleaseAddTitle": "Please add a title.",
  "pleaseAddStartDate": "Please add a start date.",
  "pleaseAddStartTime": "Please add a start time.",
  "pleaseAddEndDate": "Please add a end date.",
  "pleaseAddEndTime": "Please add a end time.",
  "pleaseSelectMaxMembers": "Please select a maximum members.",
  "pleaseSelectMinAge": "Please select minimum age.",
  "pleaseCorrectMinAge": "Please correct minimum age to be 18.",
  "pleaseSelectMaxAge": "Please select maximum age.",
  "pleaseCorrectMaxAge": "Please correct maximum age to be greater than 18.",
  "maxAgeGreaterThanMin": "Maximum age must be greater than minimum age.",
  "pleaseAddLocation": "Please add a location.",
  "pleaseSelectCategory": "Please select a category.",
  "pleaseAddDescription": "Please add a description.",
  "markedAsFavourite": "Marked as favourite plan.",
  "failedFavourite": "Failed favourite plan:",
  "removedFavourite": "You have successfully remove favorite plan.",
  "failedRemoveFavourite": "Failed to remove favorite:",
  "updatedPlanStatus": "You have successfully updated plan status.",
  "accountCreatedSuccessfully": "Account created successfully",
  "pleaseValidPassword": "Please fill in a valid password",
  "pleaseValidEmail": "Please fill in a valid email address",
  "done": "Done",
  "LANGUAGE": "LANGUAGE",
  "favourites": "Favourites",
  "Age": "Age",
  "reset": "Reset",
  "my_plan": "My Plan",
};
