Map<String, String> esES = {
  "findingNextPlan": "Buscando tu próximo plan...",
  "getHelp": "Obtener ayuda",
  "welcomeBack": "¡Bienvenido de nuevo!",
  "loginSubtitle": "Por favor ingresa tus credenciales para comenzar.",
  "emailAddress": "Correo electrónico",
  "password": "Contraseña",
  "forgotPassword": "¿Olvidaste tu contraseña?",
  "rememberMe": "Recuérdame",
  "continueButton": "Continuar",
  "orSignIn": "o inicia sesión",
  "dontHaveAccount": "¿No tienes una cuenta?",
  "register": "Registrarse",
  "forgotPasswordTitle": "Olvidé mi contraseña",
  "forgotPasswordSubtitle":
      "Por favor ingresa el correo electrónico que comienza con",
  "sendVerificationLink": "Enviar enlace de verificación",
  "backTo": "Volver a",
  "login": "Iniciar sesión",
  "mailSent": "¡Correo enviado!",
  "mailSentDescription":
      "Hemos enviado un correo a tu dirección de email. Por favor verifica y restablece tu contraseña.",
  "checkMail": "Revisar correo",
  "resetPassword": "Restablecer contraseña",
  "resetPasswordSubtitle":
      "Por favor crea tu nueva contraseña. No la compartas con nadie de tu círculo.",
  "backToLogin": "Volver al inicio de sesión",
  "accountCreated": "¡Cuenta creada!",
  "accountCreatedDescription":
      "Has creado tu cuenta exitosamente. Disfruta el viaje",
  "goToHomePage": "Ir a la página de inicio",
  "personalInformation": "Información personal",
  "personalInfoSubtitle":
      "Por favor ingresa tu información personal para continuar.",
  "uploadProfilePhoto": "Subir foto de perfil",
  "uploadProfilePhotoSubtitle": "Por favor sube una imagen de tu rostro.",
  "basicInformation": "INFORMACIÓN BÁSICA",
  "fullName": "Nombre completo",
  "gender": "Género",
  "dateOfBirth": "Fecha de nacimiento",
  "ageRestriction": "Debes tener 18+ años para usar esta aplicación.",
  "confirm": "Confirmar",
  "location": "Ubicación",
  "biography": "Biografía",
  "autoSendPlanInfo":
      "Enviar automáticamente info del plan al contacto cuando el usuario se une a un plan",
  "emergencyContactInformation": "Información de contacto de emergencia",
  "emergencyContactSubtitle":
      "Por favor ingresa tu información de contacto en caso de emergencia.",
  "contactName": "Nombre del contacto",
  "emergencyPhoneNumber": "Número de teléfono de emergencia",
  "relationshipType": "Tipo de relación",
  "freePlan": "Plan Gratuito",
  "freePlanSubtitle":
      "Disfruta nuestros increíbles y accesibles planes de suscripción.",
  "freePlanLimit": "Límite de 2 planes por semana",
  "freePlanFilters": "Filtros: Solo distancia + categoría",
  "freePlanNotifications":
      "Notificaciones al alcanzar el límite semanal recomendando una mejora.",
  "freeMonthPremiumTrial": "PRUEBA PREMIUM GRATUITA DE 1 MES",
  "startFreeTrial": "Comenzar prueba gratuita",
  "premiumPackage": "PAQUETE PREMIUM",
  "monthly": "mensual",
  "signingInAgree": "Al iniciar sesión aceptas",
  "termsAndConditions": "Términos y condiciones",
  "and": "y nuestra",
  "privacyPolicy": "Política de privacidad",
  "selectPayment": "Seleccionar pago",
  "selectPaymentSubtitle": "Por favor selecciona el método de pago preferido.",
  "applePay": "Apple Pay",
  "debitCreditCard": "Tarjeta de débito/crédito",
  "googlePay": "Google Pay",
  "americanExpress": "American Express",
  "enterCardInformation": "Ingresar información de tarjeta",
  "back": "Atrás",
  "enterCardInfoSubtitle":
      "Por favor ingresa la información de la tarjeta mencionada en tu tarjeta de débito o crédito.",
  "cardNumber": "Número de tarjeta",
  "cardHolderName": "Nombre del titular",
  "expiryDate": "Fecha de vencimiento",
  "cvv": "CVV",
  "goodMorning": "¡Buenos días!",
  "goodAfternoon": "Buenas tardes",
  "searchHere": "Buscar aquí...",
  "active": "Activo",
  "expired": "Expirado",
  "createNewPlan": "Crear nuevo plan",
  "applyFilters": "Aplicar filtros",
  "selectPeople": "Seleccionar personas",
  "to": "Hasta",
  "selectAge": "Seleccionar edad",
  "selectDistance": "Seleccionar distancia",
  "category": "Categoría",
  "cultureAndLeisure": "Cultura y ocio",
  "natureAndOutdoors": "Naturaleza y aire libre",
  "sportsAndWellness": "Deportes y bienestar",
  "socialAndLifestyle": "Social y estilo de vida",
  "creativityAndLearning": "Creatividad y aprendizaje",
  "travelAndGetaways": "Viajes y escapadas",
  "gamingAndGeek": "Juegos y geek",
  "rest": "Descanso",
  "uploadPlanPhoto": "Subir foto del plan",
  "fileSizeMax": "Tamaño de archivo (máx. 100 mb)",
  "upload": "Subir",
  "planTitle": "Título del plan",
  "startDate": "Fecha de inicio",
  "endDate": "Fecha de fin",
  "startTime": "Hora de inicio",
  "endTime": "Hora de fin",
  "maximumMembersAllowed": "Número máximo de miembros permitidos",
  "ageMin": "Mín",
  "ageMax": "Máx",
  "description": "Descripción",
  "createPlan": "Crear plan",
  "home": "Inicio",
  "favorites": "Favoritos",
  "myPlans": "Mis planes",
  "discoverPlans": "Descubrir planes",
  "notifications": "Notificaciones",
  "userProfile": "Perfil de usuario",
  "logout": "Cerrar sesión",
  "noFavoritesYet": "Aún no hay favoritos",
  "joinedPlans": "Planes unidos",
  "members": "Miembros",
  "groupProfile": "Perfil del grupo",
  "membersInGroup": "miembros en este grupo",
  "personProfile": "Perfil de persona",
  "planDetails": "Detalles del plan",
  "completed": "Completado",
  "openGroupChat": "Abrir chat grupal",
  "dateAndTime": "Fecha y hora",
  "membersJoined": "Miembros unidos",
  "slotsLeft": "Espacios disponibles",
  "plans": "Planes",
  "noNotificationsYet": "¡Sin notificaciones aún!",
  "noNotificationsDescription": "No hay notificaciones para mostrar aún.",
  "join": "Unirse",
  "participants": "Participantes",
  "logoutConfirmation":
      "¿Estás seguro de que quieres cerrar sesión en esta aplicación?",
  "yesLogout": "Sí, cerrar sesión",
  "submit": "Enviar",
  "deleteAccount": "¿Eliminar cuenta?",
  "deleteAccountConfirmation":
      "¿Estás seguro de que quieres eliminar tu cuenta? Esto borrará todos tus datos actuales.",
  "yesDelete": "Sí, eliminar",
  "editProfile": "Editar perfil",
  "fullNameLabel": "Nombre completo",
  "personalInformationSection": "INFORMACIÓN PERSONAL",
  "update": "Actualizar",
  "changePassword": "Cambiar contraseña",
  "currentPassword": "Contraseña actual",
  "newPassword": "Nueva contraseña",
  "confirmNewPassword": "Confirmar nueva contraseña",
  "manageSubscriptions": "Gestionar suscripciones",
  "enableNotifications": "Activar notificaciones",
  "appFeedback": "Comentarios de la app",
  "deleteAccountOption": "Eliminar cuenta",
  "generalSettings": "CONFIGURACIÓN GENERAL",
  "helpAndSupport": "AYUDA Y SOPORTE",
  "planFull": "Plan lleno",
  "startDateAndTime": "Fecha y hora de inicio",
  "endDateAndTime": "Fecha y hora de fin",
  "planFullMessage": "El plan está lleno. No puedes unirte.",
  "leavePlan": "Abandonar plan",
  "typeMessageHere": "Escribe tu mensaje aquí...",
  "gallery": "Galería",
  "camera": "Cámara",
  "pleaseAddEventImage": "Por favor agrega una imagen del evento.",
  "pleaseAddTitle": "Por favor agrega un título.",
  "pleaseAddStartDate": "Por favor agrega una fecha de inicio.",
  "pleaseAddStartTime": "Por favor agrega una hora de inicio.",
  "pleaseAddEndDate": "Por favor agrega una fecha de fin.",
  "pleaseAddEndTime": "Por favor agrega una hora de fin.",
  "pleaseSelectMaxMembers":
      "Por favor selecciona el número máximo de miembros.",
  "pleaseSelectMinAge": "Por favor selecciona la edad mínima.",
  "pleaseCorrectMinAge": "Por favor corrige la edad mínima a 18.",
  "pleaseSelectMaxAge": "Por favor selecciona la edad máxima.",
  "pleaseCorrectMaxAge":
      "Por favor corrige la edad máxima para que sea mayor a 18.",
  "maxAgeGreaterThanMin": "La edad máxima debe ser mayor que la edad mínima.",
  "pleaseAddLocation": "Por favor agrega una ubicación.",
  "pleaseSelectCategory": "Por favor selecciona una categoría.",
  "pleaseAddDescription": "Por favor agrega una descripción.",
  "markedAsFavourite": "Marcado como plan favorito.",
  "failedFavourite": "Error al marcar como favorito:",
  "removedFavourite": "Has eliminado el plan de favoritos exitosamente.",
  "failedRemoveFavourite": "Error al eliminar de favoritos:",
  "updatedPlanStatus": "Has actualizado el estado del plan exitosamente.",
  "accountCreatedSuccessfully": "Cuenta creada exitosamente",
  "pleaseValidPassword": "Por favor ingresa una contraseña válida",
  "pleaseValidEmail": "Por favor ingresa una dirección de correo válida",
  "done": "Listo",
  "LANGUAGE": "Idioma",
  "favourites": "Favoritas",
  "Age": "Edad",
  "reset": "Restablecer",
  "my_plan": "Mi Plan",
};
